# Generated by Django 5.0.4 on 2024-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categories_products_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_two',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название Подкатегории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название Категории'),
        ),
    ]
