# Generated by Django 5.0.4 on 2024-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories_name_two_alter_categories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_two',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
